# Generated by Django 5.2.6 on 2025-09-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.CharField(choices=[('user', 'User'), ('agent', 'Agent'), ('admin', 'Admin')], default='user', max_length=5)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
